######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 28 01:44:14 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . core
INCLUDEPATH += . core

# Input
HEADERS += core/coreclass.h
SOURCES += core/coreclass.cpp
